name = "lxim"
mainprefix = "z"
prefix = "lxim"
author = "YonV"

[files]
include = [
    "mod.cpp",
    "README.md",
    "README*.md",
    "LICENSE",
    "3rdparty",
    "AUTHORS.txt",
    "logo_512.paa",
    "logo_512.paa"
]

exclude = ["*.psd", "*.tga"]

[version]
path = "addons/main/script_version.hpp"
