name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release-addon:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout the source code
          uses: actions/checkout@v2
        - name: Setup HEMTT
          uses: arma-actions/hemtt@v1
        - name: Run HEMTT build
          run: hemtt release --no-archive
        - name: Move release to releases folder
          run:
            version="${{ github.event.release.tag_name }}"
            mv .hemttout/release "@lxim-${{ env.VERSION }}"
        - name: Zip release
          run: zip -r "@lxim.zip" ./@lxim-${{ env.VERSION }}
        - name: Update Release with Files
          uses: softprops/action-gh-release@v1
          with:
            files: ./@lxim.zip
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

